### ISSUE TITLE
Request icon

### ISSUE THREAD

**Issue by vetash** [bitHero/bitIcon#1]
Hello! Awesome project i like it. But i need some icon for bash or sh. 
Seems like contact form on web site is broke, so i wrote there.

Thanks.

**Comment by hwkr** [comment]
Cool! I'll give it a shot today.

**Comment by hwkr** [comment]
![Release v1.2 Preview](https://cdn.rawgit.com/bitHero/bitIcon/master/src/bitIcon-release-1-2.svg)

Added script and shell in release v1.2!

**Comment by vetash** [comment]
Cool! Thank you!
